"""Add Google OAuth fields to User model

Revision ID: 3223a1adbd71
Revises: 34f350f87d1d
Create Date: 2025-07-26 08:29:59.284881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3223a1adbd71'
down_revision: Union[str, Sequence[str], None] = '34f350f87d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_google_authenticated', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_google_authenticated')
    op.drop_column('users', 'google_picture')
    op.drop_column('users', 'google_name')
    op.drop_column('users', 'google_email')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
